host: 127.0.0.1
tcpPort: 25
channels:
  file:
    enabled: true
    dirPath: /path/to/files
  telegram:
    enabled: true
    userId: 123456789
    botKey: your_telegram_bot_api_key
  slack:
    enabled: true
    userId: a1b2c3d4e5
    botKey: your_slack_app_api_key
  teams:
    enabled: false
  whatsup:
    enabled: false
