name: Other branches

on:
  push:
    branches-ignore:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Check code formating with "go fmt ./..."
        run: make fmt

      - name: Run tests
        run: make test

      - name: Build
        run: make build
